#ifndef FLASH_ADDRESSES_H
#define FLASH_ADDRESSES_H

const uint32_t COUNTDOWN_TIMER_FLASH_ADDRESS = 0;
const uint32_t DURATION_TIMER_FLASH_ADDRESS = 4;
const uint32_t STILLNESS_TIMER_FLASH_ADDRESS = 8;

const uint32_t HEARTBEAT_INTERVAL_FLASH_ADDRESS = 12;

#endif // FLASH_ADDRESSES_H